'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, Check, Copy, ExternalLink, Link2, LogOut, MessageCircle, MoreHorizontal, Pin, Plus, QrCode, Send, Settings2, Trash2, Users, WifiOff, X } from 'lucide-react';
import { Brand } from './brand';
import { PollCard, NewPoll } from './poll-card';
import { ShareDialog } from './share-dialog';
import { api, dateLabel, timeLabel } from '../lib/client';
import type { PublicMessage, Snapshot } from '../lib/types';

function MessageText({ text }: { text: string }) {
  return <>{text.split(/(https?:\/\/[^\s<>]+)/g).map((part, i) => /^https?:\/\//.test(part) ? <a key={i} href={part} target="_blank" rel="noopener noreferrer">{part}</a> : part)}</>;
}
function ChatMessage({ message, host, editable, busy, onAction, onNotice }: { message: PublicMessage; host: boolean; editable: boolean; busy: boolean; onAction: (input: Record<string, unknown>, success: string) => Promise<void>; onNotice: (message: string) => void }) {
  const [confirming, setConfirming] = useState(false);
  const teacher = message.author !== 'student'; const mine = message.mine || (host && teacher);
  async function copy() { try { await navigator.clipboard.writeText(message.url ?? message.text); onNotice('복사했어요.'); } catch { onNotice('내용을 선택해서 복사해주세요.'); } }
  return <article className={`chat-message ${mine ? 'my-message' : ''} ${teacher ? 'teacher-message' : ''}`}>
    {!mine && <span className="chat-avatar" aria-hidden="true">{teacher ? <span>강</span> : <span>수</span>}</span>}
    <div className="chat-message-body"><div className="chat-meta"><b>{message.authorName ?? '강사'}</b>{teacher && <span>강사</span>}<time dateTime={message.createdAt}>{timeLabel(message.createdAt)}</time></div>
      <div className="chat-bubble"><p><MessageText text={message.text} /></p>{message.url && <a className="chat-link" href={message.url} target="_blank" rel="noopener noreferrer"><Link2 size={16} /><span>{new URL(message.url).hostname.replace('www.', '')}</span><ExternalLink size={14} /></a>}</div>
      <details className="message-menu"><summary aria-label={`${message.text.slice(0, 20)} 메시지 메뉴`}><MoreHorizontal size={17} /></summary><div><button onClick={copy}><Copy size={14} />복사</button>{host && editable && <><button disabled={busy} onClick={() => onAction({ type: 'pin', id: message.id }, message.pinned ? '고정을 해제했어요.' : '메시지를 고정했어요.')}><Pin size={14} />{message.pinned ? '고정 해제' : '상단 고정'}</button><button disabled={busy} onClick={() => setConfirming(true)}><Trash2 size={14} />삭제</button></>}</div></details>
      {confirming && <div className="chat-delete" role="alert"><span>이 메시지를 삭제할까요?</span><button disabled={busy} onClick={() => onAction({ type: 'delete', id: message.id }, '메시지를 삭제했어요.')}>삭제하기</button><button onClick={() => setConfirming(false)}>취소</button></div>}
    </div>
  </article>;
}
function Composer({ busy, active, onAction }: { busy: boolean; active: boolean; onAction: (input: Record<string, unknown>, success: string) => Promise<void> }) {
  const [link, setLink] = useState(false); const [text, setText] = useState(''); const [url, setUrl] = useState(''); const [error, setError] = useState('');
  const textRef = useRef<HTMLTextAreaElement>(null); const urlRef = useRef<HTMLInputElement>(null);
  async function send(event: React.FormEvent) {
    event.preventDefault(); if (busy || !active) return; setError('');
    if (!text.trim()) { setError('메시지를 입력해주세요.'); textRef.current?.focus(); return; }
    if (link) { try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error(); } catch { setError('http:// 또는 https://로 시작하는 링크를 입력해주세요.'); urlRef.current?.focus(); return; } }
    try { await onAction({ type: 'message', text, url: link ? url : null }, '메시지를 보냈어요.'); setText(''); setUrl(''); setLink(false); textRef.current?.focus(); } catch { /* preserve the draft; room error reports failure */ }
  }
  return <form className="chat-composer" onSubmit={send}>
    {link && <div className="chat-url"><Link2 size={16} /><label className="sr-only" htmlFor="message-url">링크 주소</label><input id="message-url" ref={urlRef} type="url" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://" maxLength={2048} disabled={!active} /><button className="icon-button" type="button" onClick={() => setLink(false)} aria-label="링크 첨부 닫기"><X size={17} /></button></div>}
    <div className="chat-input-row"><button className={`attach-button ${link ? 'selected' : ''}`} type="button" onClick={() => setLink(!link)} aria-label="링크 첨부" aria-pressed={link} disabled={!active}><Link2 size={20} /></button><label htmlFor="message-text" className="sr-only">채팅 메시지</label><textarea id="message-text" ref={textRef} value={text} onChange={e => setText(e.target.value)} placeholder={active ? '메시지나 질문을 입력하세요.' : '지금은 채팅을 보낼 수 없어요.'} maxLength={2000} rows={1} disabled={!active} aria-invalid={Boolean(error)} aria-describedby={error ? 'composer-error' : undefined} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} /><button className="chat-send" type="submit" disabled={busy || !active} aria-label={busy ? '메시지 보내는 중' : '메시지 보내기'}><Send size={19} /></button></div>
    <div className="composer-hint"><span>{active ? 'Enter 전송 · Shift + Enter 줄바꿈' : '지난 기록은 편하게 둘러보세요.'}</span><span>{text.length}/2000</span></div>{error && <p className="error" role="alert" id="composer-error">{error}</p>}
  </form>;
}
function QuestionDialog({ busy, onAction, onClose }: { busy: boolean; onAction: (input: Record<string, unknown>, success: string) => Promise<void>; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement; const dialog = ref.current; dialog?.showModal(); return () => { dialog?.close(); previous?.focus(); }; }, []);
  return <dialog className="share-dialog question-dialog" ref={ref} aria-labelledby="question-dialog-title" onCancel={e => { e.preventDefault(); onClose(); }}><button className="dialog-close icon-button" onClick={onClose} aria-label="투표 관리 닫기"><X size={20} /></button><h2 id="question-dialog-title">새 투표 만들기</h2><p>수업 중 궁금한 것을 물어보세요.</p><NewPoll busy={busy} onAction={async (input, success) => { await onAction(input, success); onClose(); }} /></dialog>;
}
export function RoomView({ code, host, onBack, onLogout }: { code: string; host: boolean; onBack?: () => void; onLogout?: () => Promise<void> }) {
  const [data, setData] = useState<Snapshot | null>(null); const [date, setDate] = useState(''); const [error, setError] = useState(''); const [connected, setConnected] = useState(true); const [busy, setBusy] = useState(false);
  const [share, setShare] = useState(false); const [questions, setQuestions] = useState(false); const [tab, setTab] = useState<'all' | 'links'>('all'); const [notice, setNotice] = useState(''); const [history, setHistory] = useState(false); const [unread, setUnread] = useState(false);
  const noticeTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const scroller = useRef<HTMLDivElement>(null); const nearBottom = useRef(true); const forceBottom = useRef(false);
  function notify(message: string) { setNotice(message); if (noticeTimer.current) clearTimeout(noticeTimer.current); noticeTimer.current = setTimeout(() => setNotice(''), 4000); }
  useEffect(() => () => { if (noticeTimer.current) clearTimeout(noticeTimer.current); }, []);
  useEffect(() => { let stopped = false; api<Snapshot>(`/api/rooms/${code}`, { type: host ? 'start-day' : 'join' }).then(value => { if (!stopped) { setData(value); setDate(value.date); setError(''); } }).catch(e => { if (!stopped) setError(e.message); }); return () => { stopped = true; }; }, [code, host]);
  useEffect(() => {
    if (!date) return; let stopped = false; let inflight = false;
    async function refresh() { if (inflight || document.hidden) return; inflight = true; try { const value = await api<Snapshot>(`/api/rooms/${code}?date=${date}`); if (!stopped) { setData(value); setConnected(true); setError(''); } } catch (e) { if (!stopped) { setConnected(false); setError((e as Error).message); } } finally { inflight = false; } }
    refresh(); const timer = setInterval(refresh, 2000); document.addEventListener('visibilitychange', refresh); return () => { stopped = true; clearInterval(timer); document.removeEventListener('visibilitychange', refresh); };
  }, [code, date]);
  useEffect(() => { if (host || !data || data.date !== data.today || !data.active) return; const timer = setInterval(() => { if (!document.hidden) api(`/api/rooms/${code}`, { type: 'heartbeat' }).catch(() => {}); }, 15_000); return () => clearInterval(timer); }, [host, code, data?.date, data?.today, data?.active]);
  const action = useCallback(async (input: Record<string, unknown>, success: string) => { setBusy(true); try { const value = await api<Snapshot>(`/api/rooms/${code}`, { ...input, date }); if (input.type === 'message') forceBottom.current = true; setData(value); setConnected(true); setError(''); notify(success); } catch (e) { setError((e as Error).message); throw e; } finally { setBusy(false); } }, [code, date]);
  const safeAction = useCallback(async (input: Record<string, unknown>, success: string) => { try { await action(input, success); } catch { /* visible room error */ } }, [action]);
  const messages = data?.messages.filter(m => tab === 'all' || m.url || /https?:\/\//.test(m.text)) ?? []; const lastId = messages.at(-1)?.id;
  function scrollLatest() { const element = scroller.current; if (element) element.scrollTop = element.scrollHeight; nearBottom.current = true; setUnread(false); }
  useEffect(() => { nearBottom.current = true; setUnread(false); }, [date, tab]);
  useEffect(() => { if (nearBottom.current || forceBottom.current) { scrollLatest(); forceBottom.current = false; } else setUnread(true); }, [lastId, date, tab]);
  const pinned = data?.messages.find(m => m.pinned); const editable = Boolean(data && data.date === data.today); const active = Boolean(data?.active && editable && connected);
  return <div className="live-room"><a className="skip-link" href="#main">본문으로 건너뛰기</a><header className="live-header"><Brand /><div className="live-header-actions">{host ? <span className="live-role">강사</span> : <Link className="live-host-link" href={`/host?room=${code}`} aria-label="강사 로그인">강사</Link>}{host && onLogout && <button className="icon-button" aria-label="로그아웃" onClick={() => onLogout().catch(e => setError(e.message))}><LogOut size={18} /></button>}<button className="live-share" onClick={() => setShare(true)}><QrCode size={18} /><span>참여 링크</span></button></div></header>
    {!data ? <main id="main" className="live-loading"><img src="/branding/hjsy-mark-corporate.svg" width="64" height="64" alt="" /><h1>{error ? '강의실에 연결하지 못했어요.' : '강의실을 열고 있어요.'}</h1>{error ? <><p role="alert">{error}</p><button className="primary" onClick={() => window.location.reload()}>다시 연결</button><Link href="/join">다른 강의실 참여</Link></> : <p role="status">채팅과 투표를 준비하고 있어요.</p>}</main> : <>
      <section className="live-title"><div className="live-title-copy"><span className="live-kicker"><span className={connected && data.active ? 'signal-dot' : 'signal-dot offline'} />{!connected ? '연결 확인 중' : data.active ? 'LIVE CLASS' : editable ? '강의 종료' : '지난 강의'}<span className="live-code">{code}</span>{data.mode === 'local' && <span className="local-label">{data.demo ? '미리보기' : '로컬'}</span>}</span><h1>{data.title}</h1></div><div className="live-room-actions"><span className="live-online"><Users size={16} /><b>{data.online}</b><span>접속 중</span></span><details className="room-settings"><summary aria-label="강의실 설정"><Settings2 size={20} /></summary><div className="settings-panel"><label htmlFor="lecture-date">강의 날짜</label><select id="lecture-date" value={date} onChange={e => setDate(e.target.value)}>{data.dates.map(d => <option key={d} value={d}>{dateLabel(d)}{d === data.today ? ' · 오늘' : ''}</option>)}</select>{data.polls.some(p => p.archived) && <button aria-pressed={history} onClick={() => setHistory(!history)}>{history ? '현재 투표 보기' : '이전 투표 결과 보기'}</button>}<p>채팅과 투표는 2초마다 갱신돼요.</p>{data.mode === 'local' && <p>현재 로컬 미리보기입니다. 예시 메시지 외의 채팅·응답 수는 실제 참여로 집계됩니다.</p>}{host && editable && <button disabled={busy} onClick={() => safeAction({ type: 'active', active: !data.active }, data.active ? '오늘 강의를 종료했어요.' : '강의를 다시 시작했어요.')}>{data.active ? '오늘 강의 종료' : '강의 다시 시작'}</button>}{host && onBack ? <button onClick={onBack}><ArrowLeft size={15} />내 강의실 목록</button> : <Link href="/join"><ArrowLeft size={15} />다른 강의실 참여</Link>}</div></details></div></section>
      {error && <div className="live-error" role="alert"><WifiOff size={17} /><span>{error}</span><button aria-label="오류 메시지 닫기" onClick={() => setError('')}><X size={16} /></button></div>}
      <main id="main" className="live-workspace"><aside className="live-polls" aria-labelledby="polls-title"><div className="live-polls-heading"><h2 id="polls-title">실시간 투표</h2><span>{host ? '수강생 응답을 확인하세요' : '선택하면 바로 집계됩니다'}</span>{host && active && <button className="icon-button" onClick={() => setQuestions(true)} aria-label="새 투표 만들기"><Plus size={17} /></button>}</div><div className="live-poll-scroll">{data.polls.filter(p => history ? p.archived : !p.archived).map(poll => <PollCard key={poll.id} poll={poll} host={host && !history} active={active && !history} busy={busy} onAction={safeAction} />)}{history && !data.polls.some(p => p.archived) && <p className="poll-empty">이전 투표 결과가 아직 없어요.</p>}</div><div className="live-poll-note"><span>이름 없이 집계 · 응답 변경 가능</span>{data.polls.some(p => p.archived) && <button aria-pressed={history} onClick={() => setHistory(!history)}>{history ? '현재 투표' : '이전 결과'}</button>}</div></aside>
        <section className="live-chat" aria-labelledby="chat-title"><div className="live-chat-heading"><h2 id="chat-title"><MessageCircle size={20} />실시간 채팅</h2><div className="chat-filters" role="group" aria-label="채팅 필터"><button className={tab === 'all' ? 'selected' : ''} aria-pressed={tab === 'all'} onClick={() => setTab('all')}>전체</button><button className={tab === 'links' ? 'selected' : ''} aria-pressed={tab === 'links'} onClick={() => setTab('links')}><Link2 size={14} />링크</button></div></div>
          {pinned && <div className="chat-pinned"><Pin size={14} /><span>고정</span>{pinned.url ? <a href={pinned.url} target="_blank" rel="noopener noreferrer">{pinned.text}</a> : <p>{pinned.text}</p>}{pinned.url && <ExternalLink size={13} />}</div>}
          <div className="chat-scroll" ref={scroller} tabIndex={0} aria-label="채팅 메시지 목록" onScroll={() => { const el = scroller.current; if (el) { nearBottom.current = el.scrollHeight - el.scrollTop - el.clientHeight < 65; if (nearBottom.current) setUnread(false); } }}><p className="chat-date">{dateLabel(data.date)}{data.demo ? ' · 예시 강의실' : ''}</p><div role="log" aria-live="polite" aria-relevant="additions" aria-label="실시간 채팅 메시지">{messages.map(message => <ChatMessage key={message.id} message={message} host={host} editable={editable} busy={busy} onAction={safeAction} onNotice={notify} />)}</div>{messages.length === 0 && <div className="chat-empty"><img src="/branding/hjsy-mark-corporate.svg" alt="" width="64" height="64" /><h3>{tab === 'links' ? '공유된 링크가 아직 없어요.' : '아직 메시지가 없습니다.'}</h3><p>{tab === 'links' ? '링크가 담긴 메시지가 여기에 모여요.' : '메시지나 실습 링크를 공유해보세요.'}</p></div>}</div>
          {unread && <button className="new-messages" onClick={scrollLatest}><ArrowDown size={15} />새 메시지 보기</button>}<Composer busy={busy} active={active} onAction={action} />
        </section></main></>}
    <div className={`toast ${notice ? 'visible' : ''}`} role="status" aria-live="polite">{notice && <><Check size={17} /><span>{notice}</span></>}</div>{share && <ShareDialog code={code} onClose={() => setShare(false)} />}{questions && <QuestionDialog busy={busy} onAction={action} onClose={() => setQuestions(false)} />}
  </div>;
}
