import { createRoot } from 'react-dom/client';
import { RoomView } from '../components/room-view';
import { Host } from '../components/host';
import { Entry } from '../components/entry';
import { MAIN_ROOM_CODE } from '../lib/types';
import '../app/globals.css';
import '../app/live-room.css';
import '../app/corporate.css';
const path = window.location.pathname.replace(/\/$/, '') || '/';
const match = /^\/room\/([A-Z0-9]{6})$/.exec(path);
const view = path === '/' ? <RoomView code={MAIN_ROOM_CODE} host={false} /> : path === '/host' ? <Host /> : match ? <RoomView code={match[1]} host={false} /> : <Entry preview={false} />;
createRoot(document.getElementById('root')!).render(view);
